### ISSUE TITLE
`devide-network` should warn if parts is a wrong number

### ISSUE THREAD

**Issue by shlomi-nx** [gersak/clojure.network.ip#1]
`devide-network` should warn if `parts` argument is not a power of two. At the moment, it simply throws an `NPE` on expression `(+ mask delta-mask)` since `delta-mask` is nil.

Also, the name has a spelling error, it should be `divide-network` instead :)

**Comment by gersak** [comment]
Hi, 

Tnx for your suggestions. You are right on both points. I've changed code to throw assertion in  *devide-network* as you suggested. As well as correcting misspelling of the function itself, so now it is called divide-network.

New build is available in version 0.1.3-SNAPSHOT
